services:
  freqtrade:
    image: freqai
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./init.sh:/freqtrade/init.sh"  # Mapeia o script para o contêiner
    ports:
      - "0.0.0.0:8080:8080"
    entrypoint: ["/bin/sh", "/freqtrade/init.sh"]
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config-torch.json
      --strategy AlexStrategyFinalV9Hyper
